// @ts-check
// E2E: 17-cog (@geoleaf-plugins/cog) — deploy-full (port 8768), LAZY.
//
// Plugin-validation suite. ⚠️ This header said "EAGER … no `plugins.load`
// needed" until 2026-08-07, and the move to lazy made it false: cog's
// `<script>` tag left `index.html` for a gated `registerLazy` in `init.js`.
// It was the heaviest of the plugins — 99.8 KB gz on the critical path of
// EVERY load, for an API most pages never call.
//
// The plugin has no runtime config (INV-CONFIG not applicable) and is pure
// API: GeoLeaf.COG.{addLayer, removeLayer, getInfo}. Nothing loads it on its
// own — no listener, no toolbar slot, no declarative layer — so the consumer
// requests it, here as in a host application.
//
// A tiny real GeoTIFF (e2e/fixtures/sample-cog.tif, 16x16 RGB, EPSG:4326, bbox
// [-54,3,-53,4]), generated in-repo by fixtures/_gen-cog.cjs via geotiff.writeArrayBuffer,
// is served through page.route with HTTP Range support so the REAL bundled geotiff.js
// decodes real bytes (Range 206). No build/profile change required.
//
// Coverage:
//   - on-demand load + API surface + plugin registered
//   - getInfo()    → bounds / width / height / bandCount / overviewCount / epsg
//                    (epsg===4326 LOCKS the epsg fix: extractEpsg via image.getGeoKeys())
//   - addLayer()   → image source + raster layer injected on the map
//   - HTTP 206/200 → the .tif is fetched over (intercepted) HTTP, not stubbed in JS
//   - opacity + handle.update({opacity}) → raster-opacity re-applied
//   - handle.remove() / removeLayer()    → source + layer removed, safe when absent
//   - guards: invalid / non-http URL reject
//
// NOTE: deploy-full ships a PWA service worker → serviceWorkers:'block'. Run after
// `npm run build:deploy:all`.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { test, expect } from "@playwright/test";
import { baseURL } from "./helpers/base-url.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

test.use({ baseURL: baseURL("full"), serviceWorkers: "block" });

// Tiny real GeoTIFF fixture (generated by e2e/fixtures/_gen-cog.cjs).
const COG_BYTES = fs.readFileSync(path.join(__dirname, "fixtures", "sample-cog.tif"));
// Same-origin path (no CORS); intercepted by page.route before it reaches http-server.
const COG_PATH = "/sample-cog.tif";
// Expected metadata baked into the fixture.
const EXPECTED = { width: 16, height: 16, bandCount: 3, overviewCount: 0, epsg: 4326 };
const EXPECTED_BOUNDS = [-54, 3, -53, 4];

const SW_NOISE = /SWRegister|ServiceWorker|serviceworker/i;
const cogErrors = (arr) => arr.filter((t) => /cog|geotiff|tiff/i.test(t) && !SW_NOISE.test(t));

/**
 * Serves the fixture for any request to *.tif, honouring HTTP Range so the bundled
 * geotiff.js (fromUrl, allowFullFile:false) exercises its real partial-read path.
 */
async function routeCog(page) {
    await page.route("**/sample-cog.tif", (route) => {
        const range = route.request().headers()["range"];
        const total = COG_BYTES.length;
        const baseHeaders = {
            "Content-Type": "image/tiff",
            "Accept-Ranges": "bytes",
            "Access-Control-Allow-Origin": "*",
        };
        if (range) {
            const m = /bytes=(\d+)-(\d*)/.exec(range);
            const start = m ? parseInt(m[1], 10) : 0;
            const end = m && m[2] ? Math.min(parseInt(m[2], 10), total - 1) : total - 1;
            const chunk = COG_BYTES.subarray(start, end + 1);
            route.fulfill({
                status: 206,
                headers: {
                    ...baseHeaders,
                    "Content-Range": `bytes ${start}-${end}/${total}`,
                    "Content-Length": String(chunk.length),
                },
                body: chunk,
            });
        } else {
            route.fulfill({
                status: 200,
                headers: { ...baseHeaders, "Content-Length": String(total) },
                body: COG_BYTES,
            });
        }
    });
}

/**
 * Installs the .tif route, navigates, waits for the map, LOADS the lazy COG plugin, waits
 * for the map to settle, and returns the page/console-error and .tif response collectors.
 */
async function boot(page) {
    const errors = [];
    const consoleErrors = [];
    const tifResponses = [];
    // Sentinel for the stability watcher at the function's end. `-1` can equal
    // no real count, so the first round is never counted as "stable".
    let lastSourceCount = -1;
    page.on("pageerror", (err) => errors.push(err.message));
    page.on("console", (msg) => {
        if (msg.type() === "error") consoleErrors.push(msg.text());
    });
    page.on("response", (resp) => {
        if (resp.url().includes(".tif"))
            tifResponses.push({ url: resp.url(), status: resp.status() });
    });
    await routeCog(page);
    await page.goto("/");
    await expect(page.locator("#geoleaf-map")).toBeVisible({ timeout: 15000 });
    await page.waitForFunction(
        () => {
            const m = /** @type {any} */ (window).GeoLeaf?.Core?.getMap?.()?.getNativeMap?.();
            return !!m && typeof m.loaded === "function" && m.loaded();
        },
        null,
        { timeout: 15000 }
    );
    await page
        .locator("#gl-loader")
        .waitFor({ state: "hidden", timeout: 10000 })
        .catch(() => {});
    // `cog` IS NO LONGER EAGER. Its `<script>` tag left `index.html`
    // (99.8 KB gz, the heaviest of the plugins, on every load's critical path)
    // for a `registerLazy` in `init.js`. It is a pure API: nothing loads it on
    // its own, and that is correct — with no caller it has no work to do. The
    // consumer, here as in a host application, requests it explicitly.
    await page.evaluate(() => /** @type {any} */ (window).GeoLeaf.plugins.load("cog"));

    // 🛑 WAIT FOR THE MAP TO STABILISE, AND THE MOVE TO LAZY IS WHAT MADE IT
    // NECESSARY. `addLayer()` below measures a before/after source DELTA,
    // across an `await`. As long as 8 plugin `<script>` tags preceded the
    // boot, the profile's layers had finished arriving by the time this
    // helper returned, and the delta was 1. Boot now being shorter, two
    // layers landed DURING the await: delta 3, and a red accusing the wrong
    // culprit. The test assumed a map at rest without ever requiring it; now
    // it requires it.
    await expect
        .poll(
            async () => {
                const n = await page.evaluate(() => {
                    const m = /** @type {any} */ (
                        window
                    ).GeoLeaf?.Core?.getMap?.()?.getNativeMap?.();
                    return m ? Object.keys(m.getStyle().sources).length : -1;
                });
                const stable = n === lastSourceCount;
                lastSourceCount = n;
                return stable;
            },
            { timeout: 15000, intervals: [400, 400, 400, 600, 600, 800] }
        )
        .toBe(true);
    return { errors, consoleErrors, tifResponses };
}

// ── Boot & API surface ──────────────────────────────────────────────────────────

test("charge à la demande : GeoLeaf.COG présent après plugins.load, 3 fonctions, 0 erreur cog", async ({
    page,
}) => {
    const { errors, consoleErrors } = await boot(page);
    const api = await page.evaluate(() => {
        const gl = /** @type {any} */ (window).GeoLeaf;
        const cog = gl.COG;
        return {
            present: typeof cog === "object" && cog !== null,
            methods: ["addLayer", "removeLayer", "getInfo"].filter(
                (m) => typeof cog[m] === "function"
            ),
            // registry may expose isLoaded(); null if not present
            registered: gl.plugins?.isLoaded ? !!gl.plugins.isLoaded("cog") : null,
        };
    });
    expect(api.present).toBe(true);
    expect(api.methods).toEqual(["addLayer", "removeLayer", "getInfo"]);
    if (api.registered !== null) expect(api.registered).toBe(true);
    expect(errors).toEqual([]);
    expect(cogErrors(consoleErrors)).toEqual([]);
});

// ── getInfo() — header read through the real bundle (locks the epsg fix) ───────────

test("getInfo() reads bounds/dims/bands/epsg from the real .tif (epsg===4326)", async ({
    page,
}) => {
    const { errors, tifResponses } = await boot(page);
    const info = await page.evaluate(async (path) => {
        const url = location.origin + path;
        return await /** @type {any} */ (window).GeoLeaf.COG.getInfo(url);
    }, COG_PATH);
    console.log("GETINFO", JSON.stringify(info));
    expect(info.width).toBe(EXPECTED.width);
    expect(info.height).toBe(EXPECTED.height);
    expect(info.bandCount).toBe(EXPECTED.bandCount);
    expect(info.overviewCount).toBe(EXPECTED.overviewCount);
    // The epsg fix: extractEpsg() now reads image.getGeoKeys() (geotiff 3.x).
    expect(info.epsg).toBe(EXPECTED.epsg);
    info.bounds.forEach((v, i) => expect(Math.abs(v - EXPECTED_BOUNDS[i])).toBeLessThan(1e-6));
    expect(errors).toEqual([]);
    // The header read hit the network (intercepted) — real decode, not a JS stub.
    expect(tifResponses.some((r) => r.status === 206 || r.status === 200)).toBe(true);
});

// ── addLayer() — image source + raster layer injected on the map ──────────────────

test("addLayer() injects an image source + raster layer on the map", async ({ page }) => {
    const { errors } = await boot(page);
    const res = await page.evaluate(async (path) => {
        const map = /** @type {any} */ (window).GeoLeaf.Core.getMap().getNativeMap();
        const beforeSources = Object.keys(map.getStyle().sources).length;
        const beforeLayers = map.getStyle().layers.length;
        let id;
        let err;
        try {
            const handle = await /** @type {any} */ (window).GeoLeaf.COG.addLayer(
                location.origin + path,
                map
            );
            id = handle.id;
        } catch (e) {
            err = String((e && e.message) || e);
        }
        const style = map.getStyle();
        const src = id ? style.sources[id] : null;
        const layer = id ? style.layers.find((l) => l.id === id) : null;
        return {
            id,
            err,
            sourceType: src ? src.type : null,
            layerType: layer ? layer.type : null,
            layerSource: layer ? layer.source : null,
            sourceDelta: Object.keys(style.sources).length - beforeSources,
            layerDelta: style.layers.length - beforeLayers,
        };
    }, COG_PATH);
    console.log("ADDLAYER", JSON.stringify(res));
    expect(res.err).toBeUndefined();
    expect(res.id).toMatch(/^cog-layer-/);
    expect(res.sourceType).toBe("image");
    expect(res.layerType).toBe("raster");
    expect(res.layerSource).toBe(res.id);
    // ⚠️ MEASURED UNDER `taskset -c 0,1` on 2026-08-19, three runs:
    // `sourceDelta` and `layerDelta` are **1** every time.
    //
    // 🔻 This spec was one of the two named instances of a "green on 16
    // cores, red on 4" line, with the symptom "expects 1 layer, receives 3 —
    // a count not isolated from what precedes". **The symptom does not
    // reproduce, and the diagnosis could no longer apply anyway**: the count
    // IS isolated — `beforeLayers` is captured in the same `evaluate`, and
    // has been since 2026-06-16, two months before the symptom was written.
    // It measures a delta, not a total: what precedes cannot skew it.
    //
    // 📌 A symptom stays attached to its line long after the code made it
    // impossible. Re-reading it in the file costs less than believing it.
    expect(res.sourceDelta).toBe(1);
    expect(res.layerDelta).toBe(1);
    expect(errors).toEqual([]);
});

// ── opacity + handle.update() — raster-opacity applied then updated ────────────────

test("addLayer({opacity}) then handle.update({opacity}) re-applies raster-opacity", async ({
    page,
}) => {
    const { errors } = await boot(page);
    const res = await page.evaluate(async (path) => {
        const map = /** @type {any} */ (window).GeoLeaf.Core.getMap().getNativeMap();
        const handle = await /** @type {any} */ (window).GeoLeaf.COG.addLayer(
            location.origin + path,
            map,
            { id: "e2e-cog", opacity: 0.5 }
        );
        const initial = map.getPaintProperty("e2e-cog", "raster-opacity");
        await handle.update({ opacity: 0.3 });
        const afterUpdate = map.getPaintProperty("e2e-cog", "raster-opacity");
        const stillThere = !!map.getStyle().sources["e2e-cog"];
        return { initial, afterUpdate, stillThere };
    }, COG_PATH);
    console.log("OPACITY", JSON.stringify(res));
    expect(res.initial).toBe(0.5);
    expect(res.afterUpdate).toBe(0.3);
    expect(res.stillThere).toBe(true);
    expect(errors).toEqual([]);
});

// ── handle.remove() / removeLayer() — teardown is clean and idempotent ────────────

test("handle.remove() and removeLayer() remove the source/layer and are safe when absent", async ({
    page,
}) => {
    const { errors } = await boot(page);
    const res = await page.evaluate(async (path) => {
        const cog = /** @type {any} */ (window).GeoLeaf.COG;
        const map = /** @type {any} */ (window).GeoLeaf.Core.getMap().getNativeMap();
        const handle = await cog.addLayer(location.origin + path, map, { id: "e2e-cog-rm" });
        const present = !!map.getStyle().sources["e2e-cog-rm"];
        handle.remove();
        const afterRemove = !!map.getStyle().sources["e2e-cog-rm"];
        let secondRemoveThrew = false;
        try {
            cog.removeLayer(map, "e2e-cog-rm"); // already gone → must not throw
        } catch {
            secondRemoveThrew = true;
        }
        return { present, afterRemove, secondRemoveThrew };
    }, COG_PATH);
    console.log("REMOVE", JSON.stringify(res));
    expect(res.present).toBe(true);
    expect(res.afterRemove).toBe(false);
    expect(res.secondRemoveThrew).toBe(false);
    expect(errors).toEqual([]);
});

// ── Guards — invalid / non-http URL reject with TypeError ─────────────────────────

test("rejects an invalid URL and a non-http(s) URL", async ({ page }) => {
    await boot(page);
    const res = await page.evaluate(async () => {
        const cog = /** @type {any} */ (window).GeoLeaf.COG;
        const map = /** @type {any} */ (window).GeoLeaf.Core.getMap().getNativeMap();
        const out = { invalidErr: null, ftpErr: null };
        try {
            await cog.getInfo("not-a-url");
        } catch (e) {
            out.invalidErr = String((e && e.message) || e);
        }
        try {
            await cog.addLayer("ftp://example.com/x.tif", map);
        } catch (e) {
            out.ftpErr = String((e && e.message) || e);
        }
        return out;
    });
    expect(res.invalidErr).toMatch(/COG|URL/i);
    expect(res.ftpErr).toMatch(/http|protocol/i);
});
